name: printer_test
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image: any

  # inDevice pritner
  sunmi_printer_plus: ^4.1.1

  # for wifi/lan printer
  esc_pos_printer: ^4.1.0

  # need for both wifi/lan/bluetooth
  esc_pos_utils: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/data/order_data_bn.json
    - lib/data/order_data_en.json